# Site settings
title: Your awesome title
email: dev.uiux@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://devuiux.github.io/jekyll_mdl/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  devuiux

# Build settings
markdown: kramdown

url: "https://devuiux.github.io/jekyll-mdl"
urlimg: "https://devuiux.github.io/jekyll-mdl/images"

# url: "http://localhost:4000"
# urlimg: "http://localhost:4000/images"

# Outputting
permalink: /:categories/:title/
post_dirs: false